# Generated by Django 4.2.6 on 2023-10-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_read_blog', 'Can read the blog'), ('can_add_blog', 'Can add more blog'), ('can_update_blog', 'Can update blog'), ('can_delete_blog', 'Can delete blog')]},
        ),
    ]
