# Generated by Django 4.2.6 on 2023-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number_read',
            field=models.IntegerField(default=0),
        ),
    ]
